#!/usr/bin/env python3
"""
Adds the newsletter signup block to every case page and to the archive.

Before running, set ACTION below.

  Kit (ConvertKit)      Grow > Landing Pages & Forms > create an inline form,
                        then Embed > HTML. Copy the form's action URL, which
                        looks like:  https://app.kit.com/forms/1234567/subscriptions
                        Set MODE = "form".

  Substack              Set MODE = "link" and ACTION to your publication URL,
                        e.g. https://medicasehub.substack.com/subscribe
                        No form is posted; the button simply links out, so the
                        page stays exactly as fast as it is now.

Run:  python3 install_newsletter.py
"""

import re, glob, os

MODE   = "form"                                     # "form" for Kit, "link" for Substack
ACTION = "https://app.kit.com/forms/9916523/subscriptions"

CSS = (
".nlbox{border:1px solid var(--rule);border-left:3px solid var(--teal);border-radius:3px;"
"background:var(--sheet);padding:1.5rem 1.6rem;margin:3rem 0 0}"
".nlbox h2{font-family:var(--serif);font-size:1.18rem;line-height:1.25;margin:0 0 .45rem;"
"letter-spacing:-.01em;color:var(--ink)}"
".nlbox p{font-size:.92rem;line-height:1.55;color:var(--ink-2);margin:0 0 1.1rem;max-width:58ch}"
".nlbox form{display:flex;gap:.6rem;flex-wrap:wrap;align-items:center}"
".nlbox input{flex:1 1 240px;min-width:0;font-family:var(--sans);font-size:.95rem;color:var(--ink);"
"padding:.7rem .85rem;border:1px solid var(--rule);border-radius:3px;background:#fff}"
".nlbox input:focus{outline:2px solid var(--teal);outline-offset:1px;border-color:var(--teal)}"
".nlbox button,.nlbox .btn{font-family:var(--mono);font-size:.72rem;letter-spacing:.08em;"
"text-transform:uppercase;padding:.72rem 1.15rem;border-radius:3px;cursor:pointer;"
"background:var(--ink);color:var(--sheet);border:1px solid var(--ink);text-decoration:none;"
"display:inline-block;white-space:nowrap}"
".nlbox button:hover,.nlbox .btn:hover{background:var(--teal);border-color:var(--teal);color:#fff}"
".nlbox small{display:block;margin-top:.8rem;font-family:var(--mono);font-size:.68rem;"
"letter-spacing:.06em;text-transform:uppercase;color:var(--ink-3)}"
)

HEAD = "One case, written up properly, when there is one worth sending"
BLURB = ("No schedule and no filler. When a case turns out to have something in it that is "
         "worth the time to explain, it goes out. Unsubscribe in one click.")
FOOT = 'Free &#183; no spam &#183; your address is never shared &#183; <a href="https://kit.com/features/forms" rel="nofollow noopener" target="_blank" style="color:inherit">built with Kit</a>'

if MODE == "form":
    INNER = (f'<form action="{ACTION}" method="post" target="_blank">'
             '<label for="nl-email" style="position:absolute;left:-9999px">Email address</label>'
             '<input id="nl-email" type="email" name="email_address" required '
             'placeholder="your@email.com" autocomplete="email">'
             '<button type="submit">Subscribe</button></form>')
else:
    INNER = (f'<p style="margin-bottom:0"><a class="btn" href="{ACTION}" '
             'rel="noopener" target="_blank">Subscribe</a></p>')

BLOCK = (f'<section class="nlbox" aria-labelledby="nl-h">'
         f'<h2 id="nl-h">{HEAD}</h2><p>{BLURB}</p>{INNER}'
         f'<small>{FOOT}</small></section>')


def install(path):
    s = open(path, encoding="utf-8").read()
    if 'class="nlbox"' in s:
        return False
    if ".nlbox{" not in s:
        s = s.replace("</style>", CSS + "</style>", 1)
    # case pages: above the related-cases list
    if '<section class="rel">' in s:
        s = s.replace('<section class="rel">', BLOCK + "\n" + '<section class="rel">', 1)
    # homepage: after the three-column "why" block, above the footer
    elif '<footer class="fb">' in s:
        s = s.replace('</main>', BLOCK + "\n</main>", 1)
    else:
        return False
    open(path, "w", encoding="utf-8").write(s)
    return True


if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    # cases.html is regenerated by build.py, so the block goes on index.html instead
    targets = sorted(glob.glob(os.path.join(here, "case-*.html"))) + \
              [os.path.join(here, "index.html")]
    n = sum(1 for t in targets if os.path.exists(t) and install(t))
    print(f"{n} pages updated, mode = {MODE}")
    print(f"action = {ACTION}")
